name: build and deploy

on:
  push:
    branches:
      - prd
      - dev
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare environment (APP_VERSION, REPO_NAME, BRANCH_NAME)
        run: |
          echo "APP_VERSION=$(node printVersion.js)" >> $GITHUB_ENV
          echo "REPO_NAME=$(echo ${GITHUB_REPOSITORY#*/})" >> $GITHUB_ENV
          echo "BRANCH_NAME=$(echo $GITHUB_REF | awk -F / '{print $3}')" >> $GITHUB_ENV

      - name: assign port for prd
        if: ${{env.BRANCH_NAME == 'prd'}}
        run: |
          echo "APP_PORT=8401" >> $GITHUB_ENV

      - name: assign port for dev
        if: ${{env.BRANCH_NAME == 'dev'}}
        run: |
          echo "APP_PORT=8402" >> $GITHUB_ENV

          - name: assign port for test
        if: ${{env.BRANCH_NAME == 'test'}}
        run: |
          echo "APP_PORT=8403" >> $GITHUB_ENV
      - name: Prepare APP_DOMAIN
        run: |
          echo "APP_DOMAIN=$( echo ${{ env.BRANCH_NAME }}).api.codevteacher.com" >> $GITHUB_ENV

      - name: print environments
        run: |
          echo "${{ env.APP_VERSION }}"
          echo "${{ env.REPO_NAME }}"
          echo "${{ env.BRANCH_NAME }}"
          echo "${{ env.APP_PORT }}"
          echo "${{ env.APP_DOMAIN }}"

      
